#########################################################################
#
# Base configuration file for the Kincony KC868-AI ESP32 board
# used to control DMX lighting in the JAComms house
#
# Product: https://www.kincony.com/esp32-input-module.html
#

#########################################################################
#
# Substitutions
#
substitutions:
  # DMX ID, which is then called be I/O.
  dmx_id: "dmx-tbc"

  # Configure the i2c bus, to Kincony S3-Core Board PINs
  bus_a_sda_pin: "GPIO39"
  bus_a_scl_pin: "GPIO38"
  bus_a_frequency: "100kHz"    # Optional: 100kHz

  # Configure the ADC Ports PINS.
  analog_1: "GPIO7"
  analog_2: "GPIO6"
  analog_3: "GPIO5"
  analog_4: "GPIO4"

  # Configure the 1-Wire PINS.
  one_wire_1: "GPIO8"
  one_wire_2: "GPIO40"

  # Configure the RS485 (CAN / ModBus) ports RX & TX PINs.
  rs485_rx: "GPIO15"
  rs485_tx: "GPIO16"

  # Configure the 4G Mobile Add-on board  RX & TX PINs.
  mobile_4g_module_rxd: "GPIO17"
  mobile_4g_module_txd: "GPIO18"

  # Configure the 433Mhz RF Receiver PIN.
  rf_433mhz_receiver: "GPIO9"

########################## End of Substitutions #########################
#
# ESP Device Settings
#

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: arduino
#  flash_size: 16MB

#logger:
#  hardware_uart: USB_CDC

##########################################################################
#

# Roof Space - Front

esphome:
  name: ha-io-board-a
  friendly_name: HA I/O Board A

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin: 
    number: GPIO14
    allow_other_uses: true
  stop_bits: 2

dmx512:
  id: ${dmx_id}
  uart_id: uart_bus
  tx_pin: 
    number: GPIO14
    allow_other_uses: true
  uart_num: 1

#########################################################################
