#
#
#
web_server:
  sorting_groups:

      # Used by: athom-power-plug-no-relay.yaml and athom-power-plugs.yaml
    - id: group_electricity
      name: "Electricity Sensors"
      sorting_weight: -50


    # Used by : bme280-bus-a.yaml
    - id: group_environmental_sensors
      name: "Environmental Sensors"
      sorting_weight: -45

    # Used by : bme280-bus-b.yaml
    # TO DO - MERGE and Nunmber Bus A from 1 to 19 and Bus B from 20 to 39
    - id: group_environmental_sensors_2
      name: "Environmental Sensors"
      sorting_weight: -44

    # # Used by: athom-power-plug-no-relay.yaml and athom-power-plugs.yaml
    - id: group_energy
      name: "Energy Sensors"
      sorting_weight: -40


    # Used by: cylinder-liquid-pressure-tl136.yaml
    - id: group_tank_water_sensors
      name: "Tank Water Sensors"
      sorting_weight: -39

    # Used by: athom-power-plugs.yaml for the light and GPO Switch on Athom 
    - id: group_controls
      name: "Controls"
      sorting_weight: -30

      
    - id: group_network_info
      name: "Network Information"
      sorting_weight: -10





