****** TO BE EDITED TO UTILISE JACOMMS FRAMEWORK  *******


substitutions:
  name: "athom-energy-monitor"
  friendly_name: "Athom Energy Monitor"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  device_description: "athom bl0906 energy monitor (6 channels)"
  project_name: "Athom Technology.Athom Energy Monitor(6 Channels)"
  project_version: "2.0.1"
  update_interval: 5s
  # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as athom-smart-plug-v2.iot.home.lan in DNS/DHCP logs)
  dns_domain: ""
  # Set timezone of the smart plug. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: "Australia/Sydney"
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false"

#############################ESP32C3###########################
  bl0906_tx_pin: GPIO7
  bl0906_rx_pin: GPIO8
  button_pin:    GPIO9
  led_pin:       GPIO10
  clk_pin:       GPIO2
  mosi_pin:      GPIO3
  backlight_pin: GPIO18
  reset_pin:     GPIO4
  dc_pin:        GPIO5
  cs_pin:        GPIO6
#############################ESP32C3###########################

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: arduino
    version: recommended

preferences:
  flash_write_interval: 5min

logger:
  baud_rate: 115200
  # level: VERY_VERBOSE
  hardware_uart: UART0

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://jacomms/myhomeassistant/athom-energy-monitor-x6.yaml

packages:
  base-config:         !include common/base-configuration.yaml
  wifi-config:         !include common/network-wifi.yaml

external_components:
  - source: github://athom-tech/esp32-configs@main
    components: bl0906
    refresh: 0s

# Dentra Components - Adds 'Platform - Energy Statistics'
# https://github.com/dentra/esphome-components/tree/master/components/energy_statistics
  - source: github://dentra/esphome-components
    components: energy_statistics
    refresh: 0s

#####################################################################
#
# Globals - Store values between reboots
#

globals:

  - id: id_Energy_sum_persist
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: id_Energy_sum_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_1_persist
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: id_Energy_1_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_2_persist
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: id_Energy_2_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_3_persist
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: id_Energy_3_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_4_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  
  - id: id_Energy_4_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_5_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  
  - id: id_Energy_5_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_6_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  
  - id: id_Energy_6_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

#####################################################################
#
# Define the COMs Port
#

uart:
  tx_pin: "$bl0906_tx_pin"
  rx_pin: "$bl0906_rx_pin"
  baud_rate: 19200
  id: uart_bl0906

#####################################################################
#
# Lights
#

light:
  - platform: status_led
    name: "Status LED"
    id: blue_led
    disabled_by_default: true
    pin: $led_pin

#####################################################################
#
# Binary Sensors
#

binary_sensor:

  - platform: gpio
    pin:
      number: "$button_pin"
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
        - ON for at least 4s
        then:
          - button.press: Reset

#####################################################################
#
# Sensors
#

sensor:

  - platform: bl0906
    update_interval: "${update_interval}"

    Frequency:
      name: 'Frequency'
      id: 'Frequency'

    Temperature:
      name: 'Temperature'
      id: 'Temperature'

    Voltage:
      name: 'Voltage'
      id: 'Voltage'

#######################
#
# CT Sensor - 1
#

    Power_1:
      name: 'Power_1'
      id: 'Power_1'

    Current_1:
      name: 'Current_1'
      id: 'Current_1'

    Energy_1:
      id: 'Energy_1'

#######################
#
# CT Sensor - 2
#

    Power_2:
      name: 'Power_2'
      id: 'Power_2'
      
    Current_2:
      name: 'Current_2'
      id: 'Current_2'

    Energy_2:
      id: 'Energy_2'

#######################
#
# CT Sensor - 3
#

     Power_3:
      name: 'Power_3'
      id: 'Power_3'

    Current_3:
      name: 'Current_3'
      id: 'Current_3'

    Energy_3:
      id: 'Energy_3'

#######################
#
# CT Sensor - 4
#

    Power_4:
      name: 'Power_4'
      id: 'Power_4'

    Current_4:
      name: 'Current_4'
      id: 'Current_4'

    Energy_4:
      id: 'Energy_4'

#######################
#
# CT Sensor - 5
#

    Power_5:
      name: 'Power_5'
      id: 'Power_5'

    Current_5:
      name: 'Current_5'
      id: 'Current_5'

    Energy_5:
      id: 'Energy_5'
      
#######################
#
# CT Sensor - 6
#

    Power_6:
      name: 'Power_6'
      id: 'Power_6'

    Current_6:
      name: 'Current_6'
      id: 'Current_6'

    Energy_6:
      id: 'Energy_6'
    
  
#######################
#
# Sensors - Sum Totals
#

    Power_sum:
      name: 'Power_sum'
      id: 'Power_sum'

    Energy_sum:
      id: 'Energy_sum'
    


  - platform: copy
    name: 'Energy_sum'
    id: Energy_sum_persist
    source_id: Energy_sum
    filters:
      - lambda: |-
          if(id(id_Energy_sum_lastvalue) == 0.0  )
          {
            id(id_Energy_sum_lastvalue) = id(Energy_sum).state;
          }
          if(x < id(id_Energy_sum_persist))
          {
            float delta =  x - id(id_Energy_sum_lastvalue);
            id(id_Energy_sum_persist) += delta;
            id(id_Energy_sum_lastvalue) = x;
          }
          else
          {
            id(id_Energy_sum_persist) = x;
          }
          return id(id_Energy_sum_persist);

  - platform: copy
    name: 'Energy_1'
    id: Energy_1_persist
    source_id: Energy_1
    filters:
      - lambda: |-
          if(id(id_Energy_1_lastvalue) == 0.0  )
          {
            id(id_Energy_1_lastvalue) = id(Energy_1).state;
          }
          if(x < id(id_Energy_1_persist))
          {
            float delta =  x - id(id_Energy_1_lastvalue);
            id(id_Energy_1_persist) += delta;
            id(id_Energy_1_lastvalue) = x;
          }
          else
          {
            id(id_Energy_1_persist) = x;
          }
          return id(id_Energy_1_persist);

  - platform: copy
    name: 'Energy_2'
    id: Energy_2_persist
    source_id: Energy_2
    filters:
      - lambda: |-
          if(id(id_Energy_2_lastvalue) == 0.0  )
          {
            id(id_Energy_2_lastvalue) = id(Energy_2).state;
          }
          if(x < id(id_Energy_2_persist))
          {
            float delta =  x - id(id_Energy_2_lastvalue);
            id(id_Energy_2_persist) += delta;
            id(id_Energy_2_lastvalue) = x;
          }
          else
          {
            id(id_Energy_2_persist) = x;
          }
          return id(id_Energy_2_persist);

  - platform: copy
    name: 'Energy_3'
    id: Energy_3_persist
    source_id: Energy_3
    filters:
      - lambda: |-
          if(id(id_Energy_3_lastvalue) == 0.0  )
          {
            id(id_Energy_3_lastvalue) = id(Energy_3).state;
          }
          if(x < id(id_Energy_3_persist))
          {
            float delta =  x - id(id_Energy_3_lastvalue);
            id(id_Energy_3_persist) += delta;
            id(id_Energy_3_lastvalue) = x;
          }
          else
          {
            id(id_Energy_3_persist) = x;
          }
          return id(id_Energy_3_persist);                    

  - platform: copy
    name: 'Energy_4'
    id: Energy_4_persist
    source_id: Energy_4
    filters:
      - lambda: |-
          if(id(id_Energy_4_lastvalue) == 0.0  )
          {
            id(id_Energy_4_lastvalue) = id(Energy_4).state;
          }
          if(x < id(id_Energy_4_persist))
          {
            float delta =  x - id(id_Energy_4_lastvalue);
            id(id_Energy_4_persist) += delta;
            id(id_Energy_4_lastvalue) = x;
          }
          else
          {
            id(id_Energy_4_persist) = x;
          }
          return id(id_Energy_4_persist);

  - platform: copy
    name: 'Energy_5'
    id: Energy_5_persist
    source_id: Energy_5
    filters:
      - lambda: |-
          if(id(id_Energy_5_lastvalue) == 0.0  )
          {
            id(id_Energy_5_lastvalue) = id(Energy_5).state;
          }
          if(x < id(id_Energy_5_persist))
          {
            float delta =  x - id(id_Energy_5_lastvalue);
            id(id_Energy_5_persist) += delta;
            id(id_Energy_5_lastvalue) = x;
          }
          else
          {
            id(id_Energy_5_persist) = x;
          }
          return id(id_Energy_5_persist);

  - platform: copy
    name: 'Energy_6'
    id: Energy_6_persist
    source_id: Energy_6
    filters:
      - lambda: |-
          if(id(id_Energy_6_lastvalue) == 0.0  )
          {
            id(id_Energy_6_lastvalue) = id(Energy_6).state;
          }
          if(x < id(id_Energy_6_persist))
          {
            float delta =  x - id(id_Energy_6_lastvalue);
            id(id_Energy_6_persist) += delta;
            id(id_Energy_6_lastvalue) = x;
          }
          else
          {
            id(id_Energy_6_persist) = x;
          }
          return id(id_Energy_6_persist);

#####################################################################
