#########################################################################
#
# Environmental monitoring using ESP32-S3 chipset and BME280 sensor(s)
# for temperature, humidity, pressure & dew point.
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name  
  name: "environmental-monitor-dht"
   # Default friendly name 
  friendly_name: "Environmental Monitor DHT"
   # Description as appears in ESPHome & top of webserver page
  device_description: "ESP32 - Environmental Monitor (Temp./Humidity)"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc    
  location: ""  
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "TBC"  
   # Project Name
  project_name: "JAComms.Environmental Monitor DHT v1"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "1.0.0"

   # If true, entity should not be added to Home Assistant frontend, without the user manually enabling it.
  disable_by_default: "false"

   # DHT PIN
  dht_pin: "GPIO14"      # 
  # Location of DHT sensor.
  dht_location: "TBC"
   # Calibrate the outpute of the temperature sensor(s).
  temperature_offset: "0.0"
   # Calibrate the outpute of the humidity sensor(s).
  humidity_offset: "0.0"


########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device. 
# Must be in the local devices configuration file.
#

#esp32:
#  board: esp32dev
#  framework:
#    type: arduino

#########################################################################
#
# Remote Packages to be utilised
#

#dashboard_import:
  package_import_url: github://JAComms/myhomeassistant/esphome/environmental-monitor-dht22.yaml@main
  import_full_config: false

packages:
  base-config:      !include common/base-configuration.yaml
#  ethernet-config:  !include common/network-ethernet-lan8720.yaml
#  dht-sensor:       !include sensors/dht-22.yaml
#  wifi-config:      !include common/network-wifi.yaml


#########################################################################
