#########################################################################
#
# ESP32 Based monitoring for the Victron SmartSolar Charge Controller MPPT
# Based upon https://github.com/KinDR007/VictronMPPT-ESPHOME
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name 
  name: "victron-solar"
   # Default friendly name 
  friendly_name: "Victron Solar"
   # Description as appears in ESPHome & top of webserver page
  device_description: "Victron - SmartSolar Charge Controller MPPT 250|70"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  location: "Energy Management"
   # Project Name
  project_name: "Victron Energy.SmartSolar Charge Controller MPPT"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "0.1.6"
   # Restore the relay (Light switch) upon reboot to state:
  relay_restore_mode: RESTORE_DEFAULT_OFF
   # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as athom-smart-plug-v2.iot.home.lan in DNS/DHCP logs)
  dns_domain: ""
   # Set timezone of the device. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: "Australia/Sydney"
   # Set the duration between the sntp service polling ntp.org servers for an update
  sntp_update_interval: 6h
   # Network time servers for your region, enter from lowest to highest priority
  sntp_server_1: "0.au.pool.ntp.org"
  sntp_server_2: "1.au.pool.ntp.org"
  sntp_server_3: "2.au.pool.ntp.org"
   # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken   
  wifi_fast_connect: "true"
  
   # m5 Stack Lite PINS
   # I2C. Note scan disabled by default, if adding an I2C device, then enable in devices substitutes section
  sca_pin: "GPIO21"   
  scl_pin: "GPIO22"
  i2c_scan: "false"

   # UART_0 / COM0
  uart0_tx_pin: "GPIO26"
  uart0_rx_pin: "GPIO32"

#  UART_1 / COM1
  uart1_tx_pin: "GPIO4"
  uart1_rx_pin: "GPIO5"  

   # Accuracy of sensors / decimals places
  accuracy: "3"
   # Throttle Victron sensors to update every x seconds
  update_interval: 5s


#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://jacomms/myhomeassistant/esphome/victron-energy-smartsolar.yaml@main
  import_full_config: false

packages:
  base-config:      !include common/base-configuration.yaml
  wifi-config:      !include common/network-wifi.yaml

external_components:
# Victron Components
# https://github.com/KinDR007/VictronMPPT-ESPHOME
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
# Dentra Components - Adds 'Platform - Energy Statistics'
# https://github.com/dentra/esphome-components/tree/master/components/energy_statistics
  - source: github://roving-ronin/myhomeassistant/components@main
    refresh: 5s

#########################################################################
#
#
#
uart:
   # Connection to Victron Inverter
  - id: com0
    tx_pin: ${uart0_tx_pin}  # GPIO26 Not used! The communication is read-only
    rx_pin: ${uart0_rx_pin}  # GPIO32 Connect this this GPIO and GND to the first MPPT charger
    baud_rate: 19200
    rx_buffer_size: 256

 # - id: com1
 #   tx_pin: "${uart1_tx_pin}"  # Not connected! The communication is read-only
 #   rx_pin: "${uart1_rx_pin}"  # Connect this this GPIO and GND to the second MPPT charger
 #   baud_rate: 19200
 #   rx_buffer_size: 256
    
victron:
    # MPPT Charger #1
  - id: victron0
    uart_id: com0
    throttle: "${update_interval}"
    
    # MPPT Charger #2
#  - id: victron1
#    uart_id: com1    
#    throttle: "${update_interval}"

    # I2C Bus A
# i2c:
#  scl: "${scl_pin}"
#  sda: "${sca_pin}"
#  scan: "${i2c_scan}"
#  id: bus_a

  # Create variable to track Total_Energy, across reboots
globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'  

#########################################################################
#
# Sensors - Victron Specific
#

sensor:

  # Victron Inverter sensors
  - platform: victron
    victron_id: victron0

    max_power_yesterday:
      name: "Max Power Yesterday"
      id: max_power_yesterday
      state_class: 'measurement'
      device_class: "power"
      unit_of_measurement: 'W'
      accuracy_decimals: 1

    max_power_today:
      name: "Max Power Today"
      id: max_power_today
      state_class: 'measurement' 
      device_class: "power"
      unit_of_measurement: 'W'
      accuracy_decimals: 1
    
    yield_total:
      name: "Yield Total"
      id: yield_total
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      state_class: 'total' 
      device_class: "energy"
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}
    
    yield_yesterday:
      name: "Yield Yesterday"
      id: yield_yesterday
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      state_class: 'total'
      device_class: "energy"
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}

    yield_today:
      name: "Yield Today"
      id: yield_today
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      state_class: 'total'
      device_class: "energy"
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}
    
    panel_voltage:
      name: "Panel Voltage"
      id: panel_voltage
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:lightning-bolt-outline"
      accuracy_decimals: 2
    
    panel_power:
      name: "Panel Power"
      id: panel_power
      state_class: 'measurement'
      device_class: "power"
      unit_of_measurement: 'W'
#      icon: "mdi:lightning-bolt-outline"
      accuracy_decimals: 1

    battery_voltage:
      name: "Battery Voltage"
      id: battery_voltage
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:lightning-bolt-outline"
      accuracy_decimals: 2

    battery_voltage_2:
      name: "Battery Voltage 2"
      id: battery_voltage_2
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:lightning-bolt-outline"
      accuracy_decimals: 2      

    battery_voltage_3:
      name: "Battery Voltage 3"
      id: battery_voltage_3
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:lightning-bolt-outline"
      accuracy_decimals: 2 
        
# This many not work for MPPT
    battery_current:
      name: "Battery Current"
      id: battery_current
      state_class: 'measurement'
      device_class: "current"
      unit_of_measurement: 'A'
#      icon: "mdi:current-dc"
      accuracy_decimals: 1

# This many not work for MPPT
    battery_current_2:
      name: "Battery Current 2"
      id: battery_current_2
      state_class: 'measurement'
      device_class: "current"
      unit_of_measurement: 'A'
#      icon: "mdi:current-dc"
      accuracy_decimals: 1    

# This many not work for MPPT
    battery_current_3:
      name: "Battery Current 3"
      id: battery_current_3
      state_class: 'measurement'
      device_class: "current"
      unit_of_measurement: 'A'
#      icon: "mdi:current-dc"
      accuracy_decimals: 1    

    day_number:
      name: "Day Number"
      id: day_number
      state_class: 'total_increasing'
 #     icon: "mdi:calendar-today"
      entity_category: diagnostic
      internal: True      

    charging_mode_id:
      name: "Charging Mode ID"
      id: charging_mode_id
      icon: "mdi:identifier"
      internal: True
    
    error_code:
      name: "Error Code"
      id: error_code
      internal: True
    
    tracking_mode_id:
      name: "Tracking Mode ID"
      id: tracking_mode_id
      icon: "mdi:identifier"
      internal: True

    load_current:
      name: "Load Current"
      id: load_current
      state_class: 'measurement'
      device_class: "current"
      unit_of_measurement: 'A'
#      icon: "mdi:current-ac"    # Change this to current-dc, if it is a  DC Load

#    ac_out_voltage:
#      name: "AC Out Voltage"
#      id: ac_out_voltage
#      state_class: 'measurement'
#      device_class: "voltage"
#      unit_of_measurement: 'V'
#      icon: "mdi:current-ac"    # Change this to current-dc, if it is a  DC Load      

#    ac_out_current:
#      name: "AC Out Current"
#      id: ac_out_current
#      state_class: 'measurement'
#      device_class: "current"
#      unit_of_measurement: 'A'
#      icon: "mdi:current-ac"

#    ac_out_apparent_power:
#      name: "AC Out Power - Apparent"
#      id: ac_out_power_apparent
#      state_class: 'measurement'
#      device_class: "apparent_power"
#      unit_of_measurement: 'W'
#      icon: "mdi:lightning-bolt-outline"

    device_mode_id:
      name: "Device Mode ID"
      id: device_mode_id
#      icon: "mdi:identifier"
      
    warning_code:
      name: "Warning Code"
      id: warning_code
#      icon: "mdi:message-alert-outline"

# No Battery Management System installed
    battery_temperature:
      name: "Battery Temperature"
      id: battery_temperature
      state_class: 'measurement'
      device_class: "temperature"
      unit_of_measurement: '°C'
#      icon: "mdi:temperature-celsius"

    instantaneous_power:
      name: "Instantaneous Power"
      id: instantaneous_power
      state_class: 'measurement'
      device_class: "power"
      unit_of_measurement: 'W'
#      icon: "mdi:lightning-bolt-outline"
      
    consumed_amp_hours:
      name: "Consumed Amp Hours"
      id: consumed_amp_hours
      state_class: 'measurement'
#      icon: "mdi:hours-12"

# No Battery Management System installed    
    state_of_charge:
      name: "Battery SoC"
      id: battery_soc
      state_class: 'total'
      device_class: "energy_storage"
      unit_of_measurement: '%'
#      icon: "mdi:battery-charging"

    time_to_go:
      name: "Time to Go"
      id: time_to_go
#      icon: "mdi:timer-check-outline"
      
    depth_of_the_deepest_discharge:
      name: "Depth of Deepest Discharge"
      id: depth_of_deepest_discharge
      state_class: 'measurement'
#      unit_of_measurement: '?'
#      icon: "mdi:numeric"
      
    depth_of_the_last_discharge:
      name: "Depth of Last Discharge"
      id: depth_of_last_discharge
      state_class: 'measurement'
#      unit_of_measurement: '?'      
#      icon: "mdi:numeric"
    
    depth_of_the_average_discharge:
      name: "Depth of Average Discharge"
      id: depth_of_the_average_discharge
      state_class: 'measurement'
#      unit_of_measurement: '?'      
#      icon: "mdi:numeric"
      
    number_of_charge_cycles:
      name: "Number of Charge Cycles"
      id: number_of_charge_cycles
      state_class: 'measurement'
#      icon: "mdi:counter"
      
    number_of_full_discharges:
      name: "Number of Full Discharges"
      id: number_of_full_discharges
      state_class: 'measurement'
#      icon: "mdi:counter"
      
    cumulative_amp_hours_drawn:
      name: "Cumulative Amp Hours Drawn"
      id: cumulative_amp_hours_drawn
      state_class: 'total_increasing'
#      icon: "mdi:numeric"
    
    min_battery_voltage:
      name: "Battery Voltage - Minimum"
      id: battery_voltage_minium
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:battery-charging-low"
    
    max_battery_voltage:
      name: "Battery Voltage - Maximum"
      id: battery_voltage_maximum
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
#      icon: "mdi:battery-charging-high"
      
    last_full_charge:
      name: "Last Full Charge"
      id: last_full_charge
#      icon: "mdi:calendar-range"
      
    number_of_automatic_synchronizations:
      name: "Number of Automatic Synchronizations"
      id: number_of_automatic_synchronizations
#      icon: "mdi:battery-sync-outline"
      
    number_of_low_main_voltage_alarms:
      name: "Number of Low Main Voltage Alarms"
      id: number_of_low_main_voltage_alarms
      state_class: 'measurement'
 #     icon: "mdi:counter"
      
    number_of_high_main_voltage_alarms:
      name: "Number of High Main Voltage Alarms"
      id: number_of_high_main_voltage_alarms
      state_class: 'measurement'
#      icon: "mdi:counter"
      
    number_of_low_auxiliary_voltage_alarms:
      name: "Number of Low Auxiliary Voltage Alarms"
      id: number_of_low_auxiliary_voltage_alarms
      state_class: 'measurement'
#      icon: "mdi:counter"
      
    number_of_high_auxiliary_voltage_alarms:
      name: "Number of High Auxiliary Voltage Alarms"
      id: number_of_high_auxiliary_voltage_alarms
      state_class: 'measurement'
#      icon: "mdi:counter"
      
    min_auxiliary_battery_voltage:
      name: "Auxiliary Battery Voltage - Minimum"
      id: min_auxiliary_battery_voltage
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
  #    icon: "mdi:numeric"
      
    max_auxiliary_battery_voltage:
      name: "Auxiliary Battery Voltage - Maximum"
      id: max_auxiliary_battery_voltage
      state_class: 'measurement'
      device_class: "voltage"
      unit_of_measurement: 'V'
 #     icon: "mdi:numeric"
      
    amount_of_discharged_energy:
      name: "Amount of Discharged Energy"
      id: amount_of_discharged_energy
      state_class: 'total_increasing'
      device_class: "energy"
      unit_of_measurement: 'kWh'
#      filters:
#        # Multiplication factor from W to kW is 0.001
#        - multiply: 0.001      
#      icon: "mdi:lightning-bolt-outline"
      
    amount_of_charged_energy:
      name: "Amount of Charged Energy"
      id: amount_of_charged_energy
      state_class: 'total_increasing'
      device_class: "energy"
      unit_of_measurement: 'kWh'
#      filters:
#        # Multiplication factor from W to kW is 0.001
#        - multiply: 0.001            
#      icon: "mdi:lightning-bolt-outline"

#  - platform: template
#    name: "AC Out Power"
#    id: ac_out_power
#    state_class: 'measurement'
#    device_class: "power"
#    unit_of_measurement: 'W'
#    # https://github.com/esphome/issues/issues/2793#issuecomment-988257209
#    lambda: |-
#       auto val = id(ac_out_voltage).state * id(ac_out_current).state;
#       if (isnan(val))
#          return {};
#       return val;
#    update_interval: 10s
    
#########################################################################
#
# Sensors - ESPHome generic / device sensors
#

    # Calculates the Total Energy that has been generated / passed through the device
    # in its lifetime or since last reflashed
  - platform: template
    name: "Energy Total"
    id: energy_total_sensor
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: "mdi:lightning-bolt"
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);

    # Calculates the Energy that has been generated / passed through the device for the
    # day or since rebooted (during the day)
  - platform: total_daily_energy
    name: "Energy Today"
    id: energy_total_daily
    restore: true
    power_id: panel_power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    icon: mdi:hours-24    

#####################################################################
#
# Function added by the Dentra Components
#

     # Dentra Components - Define the id of the sensor tracking 'Total Energy' used
  - platform: "energy_statistics"
    total: energy_total_sensor

     # Dentra Components - Adds Energy Yesterday
    energy_yesterday:
      name: "Energy Yesterday"
      accuracy_decimals: 3

     # Dentra Components - Adds Energy Week
    energy_week:
      name: "Energy Week"
      accuracy_decimals: 3

     # Dentra Components - Adds Energy Month
    energy_month:
      name: "Energy Month"
      accuracy_decimals: 3

#########################################################################
#
# Binary Sensors - Victron
#

binary_sensor:
  - platform: victron
    victron_id: victron0
    
    load_state:
      name: "Load State"
#      icon: "mdi:state-machine"
      id: load_state
      entity_category: diagnostic
    
    relay_state:
      name: "Relay State"
#      icon: "mdi:state-machine"
      id: relay_state
      entity_category: diagnostic    

#########################################################################
#
# Text Sensors - Victron
#

text_sensor:

  - platform: victron
    victron_id: victron0

    device_type:
      name: "Device Type"
      entity_category: diagnostic

    device_mode:
      name: "Device Mode"
      icon: "mdi:auto-mode"
      entity_category: diagnostic      

    firmware_version:
      name: "Firmware Version"
#      icon: "mdi:numeric"
      entity_category: diagnostic

    serial_number:
      name: "Serial Number"
#      icon: "mdi:numeric"
      entity_category: diagnostic

    hardware_revision:
      name: "Hardware Revision"
      entity_category: diagnostic

    error:
      name: "Error"
      entity_category: diagnostic
      
    warning:
      name: "Warning"
      entity_category: diagnostic
      
    alarm_condition_active:
      name: "Alarm Condition Active"
#      icon: "mdi:alarm-light-outline"
      entity_category: diagnostic
      
    alarm_reason:
      name: "Alarm Reason"
#      icon: "mdi:alert-circle-outline"
      entity_category: diagnostic
      
    model_description:
      name: "Model Description"
      entity_category: diagnostic
      
    charging_mode:
      name: "Charging Mode"
#      icon: "mdi:battery-charging-outline"
      entity_category: diagnostic
      
    tracking_mode:
      name: "Tracking Mode"
      icon: "mdi:radar"
      entity_category: diagnostic    
    
#########################################################################
