#########################################################################
#
# Environmental monitoring using Kincony S3 Core board with JAComms HAT
# to monitor remote WISP sites with Victron battery configuration
#
   # Dallas Temp ID: 0x4f0b2374ee7fa928

##########################################################################
# VERSION UPATES:
#
# v1.0.0 - xx-May-2025 - Initial Release
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
  # Default name  
  name: "site-monitor-s3-core"
  # Default friendly name 
  friendly_name: "Site Monitor - S3 Core - Solar"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Site Monitor - Victron Solar & Battery"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Enter the remote stations site name here.
  location: "Site-name"
  # Location geographical height, in meters. Used for calculations in sensors such as BME280/BME680 and Water Tank sensors. Goulburn (673)
  location_height: "673"
  # Project Name
  project_name: "JAComms.Site Monitor - Solar"
  # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "0.2.1"
  # The phase in the locations power supply, upon which this device is utilsed. 1p = A. 3p = A, B or C.  (GPO 1 = Phase A, GPO 2 = Phase B, GPO 3 = Phase C).
  # Used to populate a Text Sensor with this information, that may be used to loadshed in future, or trace outages to electrical faults.
  power_circuit: "TBA"
  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE.
  # Use 'INFO' as at DEBUG the energy/water/gas statistics "Internal" sensors appear in the logs
  log_level: "DEBUG"


  # BME 280 / BME680 Sensor
  # Location of BME280/680 Sensor #1. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor1_location: ""
  # Location of BME280/680 Sensor #2. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor2_location: ""
  # Calibrate the outpute of the temperature sensor(s).
  temperature_1_offset: "0.0"
  temperature_2_offset: "0.0"
  # Calibrate the outpute of the pressure sensor(s).
  pressure_1_offset: "0.0"
  pressure_2_offset: "0.0"
  # Calibrate the outpute of the humidity sensor(s).
  humidity_1_offset: "0.0"
  humidity_2_offset: "0.0"


   # Enable logs to DEBUG and determine the ds18b20 address and paste below
#  ds18b20_address: "0x4f0b2374ee7fa928"
   # ds18b20 Sensor
   # Location of ds18b20 Sensor. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  ds18b20_sensor_location: ""
   # Calibrate the outpute of the temperature sensor(s).
  ds18b20_temperature_offset: "0.0"


########################## End of Substitutions #########################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://jacomms/myhomeassistant/esphome/victron-site-monitor-solar.yaml@main
  import_full_config: false


packages:
  utilities_monitor:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/common/base-configuration.yaml]
    refresh: 1d
    
  network_config:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/common/network-ethernet-w5500.yaml]
    refresh: 1d

  webserver_groups:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/common/webserver-groups.yaml]
    refresh: 5s

  bme280a_sensors:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/sensors/bme280-bus-a.yaml]
    refresh: 1h    

  dallas_temp_sensors:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/sensors/ds18b20-1wire.yaml]
    refresh: 1h   

  esp32_system_board:
    url: https://github.com/jacomms/myhomeassistant
    ref: main
    files: [esphome/boards/kincony-esp32-s3-core.yaml]
    refresh: 1d        


#packages:
#  base-config:             !include common/base-configuration.yaml              # Base configuration applied to all ESPHome devices
#  network-config:          !include common/network-ethernet-w5500.yaml          # Configure Ethernet port on this system board
#  webserver-groups:        !include common/webserver-groups.yaml                # Central file consolidating the web server groups and their sort orders
#  bme280a-sensors:         !include sensors/bme280-bus-a.yaml                   # Temperature, Humidity, Pressure sensor probe
#  dallas-temp-sensors:     !include sensors/ds18b20-1wire.yaml                  # One Wire / Dallas Temp Probe Sensors
#  esp32-system-board:      !include boards/kincony-esp32-s3-core.yaml           # Model of ESP Board being used. This is Kincony S3 Core with JAComms add-on HAT board.

#########################################################################
#
# Custom Components to be utilised - For Gas and Water Statistics
#

external_components:
  # Load energy sensors for time period based kWh consumption reporting
  - source:
      type: git
      url: https://github.com/jacomms/myhomeassistant/
      ref: main
    refresh: 0s
    components: [ energy_statistics ]

  # Load Victron MPPT sensors
  - source:
      type: git
      url: https://github.com/KinDR007/VictronMPPT-ESPHOME
      ref: main
    refresh: 0s
    components: [ victron ]

#########################################################################
#
# Web_server v3 Sort Groups - These substitutes are applied to overwrite the default ones supplied by the 
# sensor specific template file, in this case the /sensors/hc-sr04-ultrasonic.yaml file.
#

#web_server:
#  sorting_groups:

#     name: "Environmental Sensors"
#     sorting_weight: -45  
      
      # This sort group is used .................
#    - id: group_victron_smartshunt_sensors
#      name: "Victron - Smartshunt Sensors"
#      sorting_weight: 1

      # This sort group is used .................
 #   - id: group_victron_solar_sensors
 #     name: "Victron - Solar Sensors"
 #     sorting_weight: 5

      # This sort group is used .................
#    - id: group_victron_alarm_sensors
#      name: "Victron - Alarms Sensors"
#      sorting_weight: 10


#########################################################################
#
# Serial / COMs Port and Map VICTRON to use UART 0 and 1.
#

uart:
  - id: uart_0
    tx_pin: GPIO10
    rx_pin: GPIO11
    baud_rate: 19200
    rx_buffer_size: 256
  
  - id: uart_1
    tx_pin: GPIO12  
    rx_pin: GPIO13
    baud_rate: 19200
    rx_buffer_size: 256

victron:
  - id: victron0
    uart_id: uart_0
    throttle: 10s
  
  - id: victron1
    uart_id: uart_1
    throttle: 10s
    

##########################################################################
#
# Sensors
#

sensor:
  - platform: victron
    victron_id: victron0

    instantaneous_power:
      name: "Battery - Instantaneous Power"
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 1
        
    battery_voltage:
      name: "Battery - Voltage"   # SmartShunt - 
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 2

    battery_current:
      name: "Battery - Current"   # SmartShunt - 
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 3

    state_of_charge:
      name: "Battery - State of Charge"  # SmartShunt - 
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 4

    time_to_go:
      name: "Battery - Runtime"    # Battery Runtime
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 5

    battery_temperature:
      name: "Battery - Temperature"
      icon: 'mdi:temperature-celsius'
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 6


        
    consumed_amp_hours:
      name: "Battery - Consumed Amp Hours"
      web_server:
        sorting_group_id: group_victron_energy_sensors
        sorting_weight: 1

    cumulative_amp_hours_drawn:
      name: "Battery - Cumulative Amp Hours Drawn"
      web_server:
        sorting_group_id: group_victron_energy_sensors
        sorting_weight: 2

    amount_of_charged_energy:
      name: "Battery - Energy Charged"
      web_server:
        sorting_group_id: group_victron_energy_sensors
        sorting_weight: 3

    amount_of_discharged_energy:
      name: "Battery - Energy Discharged"
      web_server:
        sorting_group_id: group_victron_energy_sensors
        sorting_weight: 4


    midpoint_voltage_of_the_battery_bank:
      name: "Battery - Battery Bank Midpoint Voltage"
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 10

    midpoint_deviation_of_the_battery_bank:
      name: "Battery - Battery Bank Midpoint Deviation"
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 11
        
    dc_monitor_mode_id:
      name: "Battery - DC Monitor Mode ID"
      icon: 'mdi:id-card'
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 12

    auxiliary_battery_voltage:
      name: "Battery - Auxiliary Voltage"  # SmartShunt - 
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 13

    min_auxiliary_battery_voltage:
      name: "Battery - Auxiliary Minimum Voltage"
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 14
    
    max_auxiliary_battery_voltage:
      name: "Battery - Auxiliary Maximum Voltage"
      web_server:
        sorting_group_id: group_victron_smartshunt_sensors
        sorting_weight: 15




    depth_of_the_last_discharge:
      name: "Battery - Depth Last Discharge"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 11
    
    depth_of_the_average_discharge:
      name: "Battery - Depth Average Discharge"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 12

    depth_of_the_deepest_discharge:
      name: "Battery - Depth Deepest Discharge"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 13        

    number_of_charge_cycles:
      name: "Battery - Charge Cycles"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 14

    number_of_full_discharges:
      name: "Battery - Full Discharges"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 15
    
    last_full_charge:
      name: "Battery - Last Full Charge"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 16
        
    min_battery_voltage:
      name: "Battery - Min Battery Voltage"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 17
    
    max_battery_voltage:
      name: "Battery - Max Battery Voltage"
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 18


    number_of_automatic_synchronizations:
      name: "Battery - Automatic Synchronizations"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_smartshunt_statistics
        sorting_weight: 19





    number_of_high_main_voltage_alarms:
      name: "Battery - High Main Voltage Alarms"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 3

    number_of_low_main_voltage_alarms:
      name: "Battery - Low Main Voltage Alarms"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 4

    number_of_high_auxiliary_voltage_alarms:
      name: "Battery - High Auxiliary Voltage Alarms"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 5
    
    number_of_low_auxiliary_voltage_alarms:
      name: "Battery - Low Auxiliary Voltage Alarms"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 6
    

  ##########################################################################
  
  - platform: victron
    victron_id: victron1

    yield_today:
      name: "Solar - Yield Today"
      web_server:
        sorting_group_id: group_victron_power_sensors
        sorting_weight: 1

    yield_yesterday:
      name: "Solar - Yield Yesterday"
      web_server:
        sorting_group_id: group_victron_power_sensors
        sorting_weight: 2

    yield_total:
      name: "Solar - Yield Total"
      web_server:
        sorting_group_id: group_victron_power_sensors
        sorting_weight: 3

    max_power_today:
      name: "Solar - Max Power Today"
      web_server:
        sorting_group_id: group_victron_power_sensors
        sorting_weight: 4
  
    max_power_yesterday:
      name: "Solar - Max Power Yesterday"
      web_server:
        sorting_group_id: group_victron_power_sensors
        sorting_weight: 5
        
    
    panel_power:
      name: "Solar - Panel Power"
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 1

    panel_voltage:
      name: "Solar - Panel Voltage"
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 2
    
    battery_current:
      name: "Solar - Panel Current"
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 3
    
    battery_voltage:
      name: "Solar - Battery Voltage"
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 4
    
    day_number:
      name: "Solar - Day Number"
      icon: 'mdi:counter'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 5

    load_current:
      name: "Solar - Load Current"
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 6
    
    charging_mode_id:
      name: "Solar - Charging Mode ID"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 8
       
    tracking_mode_id:
      name: "Solar - Tracking Mode ID"
      icon: 'mdi:numeric'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 10
    
    error_code:
      name: "Solar - Error Code"
      icon: 'mdi:alert-box-outline'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 12
      

##########################################################################

text_sensor:
  - platform: victron
    victron_id: victron0

    alarm_condition_active:
      name: "Shunt - Alarm Condition Active"
      icon: 'mdi:alarm-light-outline'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 1

    alarm_reason:
      name: "Shunt - Alarm Reason"
      icon: 'mdi:alarm-light-outline'
      web_server:
        sorting_group_id: group_victron_alarm_sensors
        sorting_weight: 2
    
    model_description:
      name: "Shunt - Model Description"
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 1

    device_type:
      name: "Shunt - Device Type"
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 2

    firmware_version:
      name: "Shunt - Firmware Version"
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 3
    
    serial_number:
      name: "Shunt - Serial Number"
      icon: 'mdi:barcode'
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 4

    dc_monitor_mode:
      name: "Shunt - DC Monitor Mode"
      icon: 'mdi:auto-mode'
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 5


##########################################################################

  - platform: victron
    victron_id: victron1		

    charging_mode:
      name: "Solar - Charging Mode"
      icon: 'mdi:auto-mode'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 7
    
    error:
      name: "Solar - Error"
      icon: 'mdi:alert-circle-outline'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 11
    
    tracking_mode:
      name: "Solar - Tracking Mode"
      icon: 'mdi:auto-mode'
      web_server:
        sorting_group_id: group_victron_solar_sensors
        sorting_weight: 9
    
    device_type:
      name: "Solar - Device Type"
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 10
    
    firmware_version:
      name: "Solar - Firmware Version"
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 11
        
    serial_number:
      name: "Solar - Serial Number"
      icon: 'mdi:barcode'
      web_server:
        sorting_group_id: group_victron_device_information
        sorting_weight: 12

##########################################################################
