#########################################################################
#
# Water Meter with Reed Switch - Based on ESP82660
#
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name
  name: "water-meter"
   # Default friendly name  
  friendly_name: "Water Meter"
   # Description as appears in ESPHome & top of webserver page
  device_description: "DIY Water Meter - Tracking household water consumption"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  location: "Utility Meters"
   # Project Name
  project_name: "JAComms.Water Meter"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "0.1.0"
   # Restore the relay (GPO switch) upon reboot to state:
  relay_restore_mode: RESTORE_DEFAULT_OFF
   # Disable sensors
  disable_entities: "false"
  
   # GPIO PIN that the Reed Switch sensor is connected to
  water_meter_pin: ""  # 5

   # Type of ESP board being used. Used to populate the variable in /board/esp8266.yaml
  esp_board_type: "esp01_1m"   # This value is an ESP8266
   # For ESP8266 type boards, restore the saved values written to flash memory (i.e. Globals) after a reboot
  restore_from_flash: "true"

# GPIO5 - Input from Water Meter
# GPIO4 - Relay controll (Unused)


########################## End of Substitutions #########################


#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://jacomm/myhomeassistant/esphome/water-meter.yaml@main
  import_full_config: false

packages:
  base-config:     !include common/base-configuration.yaml
  wifi-config:     !include common/network-wifi.yaml
  water-sensor:    !include sensors/reed-switch-water.yaml
  esp-board:       !include boards/esp8266.yaml

#########################################################################
