substitutions:
   # Default name 
  name: "water-tanks"
   # Default friendly name 
  friendly_name: "Water Tanks"
   # Description as appears in ESPHome & top of webserver page
  device_description: "Caravan - Water Tanks (Potable)"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  room: "Utilities"
   # Project Name
  project_name: "Carava.Water Tanks"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "0.1.0"
   # Restore the relay upon reboot to state:
  relay_restore_mode: RESTORE_DEFAULT_OFF
   # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as athom-smart-plug-v2.iot.home.lan in DNS/DHCP logs)
  dns_domain: ""
   # Set timezone of the device. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: "Australia/Sydney"
   # Set the duration between the sntp service polling ntp.org servers for an update
  sntp_update_interval: 6h
   # Network time servers for your region, enter from lowest to highest priority
  sntp_server_1: "2.au.pool.ntp.org"
  sntp_server_2: "1.au.pool.ntp.org"
  sntp_server_3: "0.au.pool.ntp.org"
   # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken   
  wifi_fast_connect: "true" 
   # ADC PIN that the water pressure sensor is connected to:
  adc_pin: "35"
   # Water Tank 1 - Specifications
  tank1_height: ""     # in CM
  tank1_length: ""     # in CM
  tank1_width: ""      # in CM
  tank1_capacity: ""   # in Litres
   # Water Tank 2 - Specifications
  tank2_height: ""     # in CM
  tank2_length: ""     # in CM
  tank2_width: ""      # in CM
  tank2_capacity: ""   # in Litres  


esphome:
  #  Configures these settings to use the substituions defined below
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: '${device_description}'
  area: "${room}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO    # WARN
  baud_rate: 0
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

# Enable Home Assistant API
api:

ota:

mdns:
  disabled: false

web_server:
  port: 80  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # This spawns an AP with the device name and mac address with no password.
  ap: {}
  # Allow rapid re-connection to previously connect WiFi SSID, skipping scan of all SSID
  fast_connect: "${wifi_fast_connect}"
  # Define dns domain / suffix to add to hostname
  domain: "${dns_domain}"

captive_portal:

################################################################################
#  Sensors
################################################################################

sensor:

  #  Sensor uptime in seconds
  - platform: uptime
    name: "Uptime Seconds"
    id: uptime_seconds
    update_interval: 3min
    entity_category: diagnostic
    internal: True


# ADC Input Port 3 - 0-5V
  - platform: adc
    pin: "${adc_pin}"
    name: 'Water Tank - Voltage'
    id: water_tank_voltage
    accuracy_decimals: 3
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
    update_interval: 5s
    attenuation: 11db  #auto
    filters:
#     - multiply: 3.3
    - median: 
       window_size: 6
       send_every: 6
       send_first_at: 6
#    - calibrate_polynomial:
#       degree: 2
#       datapoints:
#          # Map from SENSOR -> TRUE value
#         - 4.15867 -> 4.01667
#         - 3.75700 -> 3.61500
#         - 3.35533 -> 3.21333
#         - 2.95367 -> 2.81167
#         - 2.55200 -> 2.41000
#         - 2.15033 -> 2.00833
#         - 1.74867 -> 1.60667
#         - 1.34700 -> 1.20500
#         - 0.94533 -> 0.80333
#         - 0.14200 -> 0.00000
    internal: true

#### Water Tank - Conversions and metrics from pressure sensor

  - platform: template
    name: "Water Tank - Level"
    id: water_tank_level
    icon: 'mdi:water-well'
    unit_of_measurement: 'cm'
    lambda: |-
        return id(water_tank_voltage).state;
    update_interval: 1s #the delta filter will ensure it only sends values when something changes. 
    filters:
      - calibrate_linear:
          # Measured value of X volt maps to Y cm
          - 4.01667 -> 241.0   # 100%
          - 3.61500 -> 216.9   #  90%
          - 3.21333 -> 192.8   #  80%
          - 2.81167 -> 168.7   #  70%
          - 2.41000 -> 144.6   #  60%
          - 2.00833 -> 120.5   #  50%
          - 1.60667 -> 96.4    #  40%
          - 1.20500 -> 72.3    #  30%
          - 0.80333 -> 48.2    #  20%
          - 0.40167 -> 24.1    #  10%
          - 0.00000 -> 0.00    #   0%

        # From https://www.sensorsone.com/measurement-to-linear-0-5v-converter/?iunit=cm&irdg=0.8452500672&ilo=0.469&ihi=4.016666&ounit=V&olo=0&ohi=5
      - delta : 0.001 #only send the result if the difference with the last sent result is higher than this
      - offset: 0.01847   # Add 0.01847cm to total, to correct to 0L when voltage is 0.469V


  - platform: template
    name: "Water Tank - %"
    id: water_tank_percent
    icon: 'mdi:water-well'
    unit_of_measurement: '%'
    update_interval: 1s #the delta filter will ensure it only sends values when something changes.     
    lambda: |-
        return id(water_tank_level).state / 241.0 * 100;
    # divide by max water level height to get a percentage. Inlet height 2410mm / tank height 2485mm. Diamter 2380mm. 10,000L
    # H 2410mm x D 2380mm = 10,721.6305 L (Full).   2410mm = 23.56kPa / .24bar / 3.42psi / 176.75 mmHg
    # local gravity = 9.79697g ms2.  1,000L = 979.697kg
#    update_interval: 1s #the delta filter will ensure it only sends values when something changes. 
    filters:
      - delta : 0.1 #only send the result if the difference with the last sent result is higher than this


  - platform: template
    name: "Water Tank - Litres"
    id: water_tank_litres
    icon: 'mdi:water-well'
    unit_of_measurement: 'L'
    lambda: |-
      if (id(water_tank_level).state <= 0) {
        return {"Empty"};
      }
      else {
        return id(water_tank_level).state / 100 * 3.14159265359 * 1.19 * 1.19 * 1000.0;
      }    # height (meters) times pi times radius (meters) squared times 1000 gives litres. 

    # This works if your water tank is a cylinder shape. Otherwise you have to use different calculations.
    # 10,000L with diamter of 2.38m = 224.7792431210859cm height
    #
    # return id(water_tank_level).state / 100 * 3.14159265359 * 1.19 * 1.19 * 1000.0;
    update_interval: 1s #the delta filter will ensure it only sends values when something changes. 
    filters:
      - delta : 0.001 #only send the result if the difference with the last sent result is higher than this
## 655.4 m or 2150.3 feet Location :-34.72653,149.72461


  - platform: copy
    source_id: water_tank_voltage
    name: 'Water Tank - Pressure (kPa)'
    id: water_tank_pressure_bar
    accuracy_decimals: 2
    device_class: pressure
    state_class: "measurement"
    unit_of_measurement: kPa
    icon: "mdi:gauge"
    filters:
#      - multiply: 3.3
      - median: 
          window_size: 6
          send_every: 6
          send_first_at: 6
      - calibrate_linear:
          # Measured value of X volt maps to y kPa
          - 4.15867 -> 23.6061428   # 100%
          - 3.75700 -> 21.2455285   #  90%
          - 3.35533 -> 18.8849142   #  80%
          - 2.95367 -> 16.5243      #  70%
          - 2.55200 -> 14.1636857   #  60%
          - 2.15033 -> 11.8030714   #  50%
          - 1.74867 -> 9.44245712   #  40%
          - 1.34700 -> 7.08184284   #  30%
          - 0.94533 -> 4.72122856   #  20%
          - 0.54367 -> 2.36061428   #  10%
          - 0.14200 -> 0.0          #   0%
        # From https://www.sensorsone.com/liquid-level-to-pressure-calculator/?lval=241&lunit=centimetres+%28cm%29&lfctr=cm&sg=1&grav=9.79508&punit=kilopascals+%28kPa%29&pfctr=kPa
        # Gouburn 655m - Local Gravity 9.79508 ms-2
    internal: true

  - platform: copy
    source_id: water_tank_voltage
    name: 'Water Tank - Pressure (psi)'
    id: water_tank_pressure_psi
    accuracy_decimals: 2
    device_class: pressure
    state_class: "measurement"
    unit_of_measurement: psi
    icon: "mdi:gauge"
    filters:
#      - multiply: 3.3
      - median: 
          window_size: 6
          send_every: 6
          send_first_at: 6
      - calibrate_linear:
          # Measured value of X volt maps to y PSI

          - 4.15867 -> 3.42378155   # 100%
          - 3.75700 -> 3.08140339   #  90%
          - 3.35533 -> 2.73902524   #  80%
          - 2.95367 -> 2.39664708   #  70%
          - 2.55200 -> 2.05426893   #  60%
          - 2.15033 -> 1.71189077   #  50%
          - 1.74867 -> 1.36951262   #  40%
          - 1.34700 -> 1.02713446   #  30%
          - 0.94533 -> 0.68475631   #  20%
          - 0.54367 -> 0.342378155  #  10%
          - 0.14200 -> 0.0          #   0%

        # https://www.sensorsone.com/liquid-level-to-pressure-calculator/?lval=241&lunit=centimetres+%28cm%29&lfctr=cm&sg=1&grav=9.79508&punit=kilopascals+%28kPa%29&pfctr=kPa
    internal: true    
